# Generated by Django 5.1.6 on 2025-02-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, upload_to='movies/'),
        ),
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.ImageField(blank=True, upload_to='movies/'),
        ),
    ]
