# Generated by Django 5.1.6 on 2025-02-14 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_actor_image_director_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='movies',
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(default='2025-01-02'),
        ),
        migrations.CreateModel(
            name='MovieSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movie')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.session')),
            ],
        ),
    ]
