# Generated by Django 5.1.6 on 2025-02-14 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_session_movies_session_date_moviesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
        migrations.AddField(
            model_name='session',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.movie'),
        ),
        migrations.AddField(
            model_name='session',
            name='ticket_price',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='ticket_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='ticket_total',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price', models.IntegerField(default=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MovieSession',
        ),
    ]
